#!/usr/bin/env bash
# Check if the number of arguments is less than 3

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extracting arguments
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Disable strict host key checking
SCP_OPTIONS="-o StrictHostKeyChecking=no"

# Transfer the file to the user's home directory on the server
scp $SCP_OPTIONS -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~
