#!/usr/bin/env bash
# installs nginx webserver into the given server
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
sudo service nginx start
