#!/usr/bin/env bash
# installs nginx webserver into the given server
sudo apt-get -y update
sudo apt-get -y install nginx
  
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html >/dev/null
sudo service nginx start
