#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

count=1

while [ $count -le 10 ]
do
	if [ $count -eq "10" ]
	then
		echo "Hi"
		echo "Best School"
		exit 0
	fi
	echo "Best School"

	((count++))
done
