#!/usr/bin/env bash
#create user

# Check if a username is provided as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Run the whoami command under the specified user
sudo -u "$1" whoami
