#!/bin/bash

#!/bin/bash

# # Prompt for passphrase
# read -s -p "Enter passphrase for RSA key: " passphrase
# echo

# Create RSA key pair with specified requirements
ssh-keygen -t rsa -b 4096 -f school -N "betty"

# echo "RSA key pair created successfully."

